apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo1-csb-server"
  description: "Demo1 CSB server"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/demo1
  providesApis: 
    - demo1-openapi