- restConfiguration:
    apiContextPath: /api-doc
    #bindingMode: json
    #bindingPackageScan: demo1-csb-server.model

- rest:
    id: rest-openapi
    openApi:
      id: openapi-configuration
      specification: https://raw.githubusercontent.com/llowinge/demo1-demo1-openapi-api/main/specification.yaml
      missingOperation: ignore